# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attDate', models.DateField()),
                ('attID', models.IntegerField()),
                ('attName', models.CharField(max_length=10)),
                ('attRange', models.CharField(max_length=10)),
                ('attStart', models.TimeField()),
                ('attEnd', models.TimeField()),
                ('attLate', models.TimeField()),
                ('attEarly', models.TimeField()),
                ('attAbsence', models.BooleanField()),
                ('attLeave', models.CharField(max_length=10)),
                ('attSpecial', models.CharField(max_length=10)),
            ],
        ),
    ]
