# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrecord',
            name='attCome',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attrecord',
            name='attGo',
            field=models.TimeField(null=True),
        ),
    ]
