# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite2', '0002_auto_20160311_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrecord',
            name='attDate',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
